### ISSUE TITLE
Killed background service with re-run foreground doesn't update properly

### ISSUE THREAD

**Issue by goldfndr** [wiglenet/wigle-wifi-wardriving#226] opened 2018-05-28 16:43 UTC
If WiGLE WiFi (hereafter "WW") is run with scanning on then other apps are opened, the WW service might be terminated due to out-of-memory conditions. It might or might not be removed from the notification area. A telltale indication is that WW's activity takes a few hundred milliseconds for the text to show up instead of nearly instantly.

After termination, the foreground activity doesn't recover gracefully:

* The hamburger menu no longer permits activity changes (e.g. can't change from Network List to Dashboard or vice versa; whatever was active last in foreground is what you're stuck with). Thankfully, the Exit item still functions and is adequate to exit the app (stopping the service) and the app can be run properly again.
* Most of the time, the upper area in Network List doesn't respond to changes (e.g. counts stay at zero or otherwise don't increase, Lat stays "(Waiting for GPS sync...)" and Lon and Speed blank even after "Now have location from gps" toast/audio).

This has been an issue for many months, still occurs on 2.29 even after force-close fix. Moto G (2013; 1 GB RAM) on stock KitKat 4.4.4 with some Xposed modules. Sorry I haven't reported it earlier.

**Comment by rksh** [comment] 2019-03-28 19:57
was this a system-initiated kill or a user-initiated kill?

**Comment by goldfndr** [comment] 2019-03-30 15:18
system-initiated. I'm pretty sure that Android ran out of memory and killed the process. I definitely didn't do a force-stop or exit or clear the recent tasks.

I don't have that phone operational any more but I might be able to reproduce it.

**Comment by rksh** [comment] 2019-05-05 20:06
haven't been able to repro, but detailed stack trace would be super helpful. will keep trying!

**Comment by goldfndr** [comment] 2019-07-27 00:43
I haven't been able to reproduce this either with a recent phone (Galaxy Note4), although I definitely have had Android run out of memory and kill the app. I'm doubtful that there'd be a stack trace, as it didn't seem to be a "crash" *per se*. So I'm fine with closing this.

**Comment by bobzilladev** [comment] 2019-12-10 15:13
Closing this since we can't reproduce it, let us know if it happens again.

**Closed by bobzilladev** 2019-12-10 15:13 UTC
