### ISSUE TITLE
[Feature Request] Allow Wigle to have Android Auto functionality.

### ISSUE THREAD

**Issue by cognitive-rift** [wiglenet/wigle-wifi-wardriving#272] opened 2018-10-08 20:59 UTC
Would be cool to have wigle as an android auto compatible app and be able to have the car's display show you a "Network list type page.

**Comment by bobzilladev** [comment] 2019-12-10 15:21
This would be fun, but none of us developers have and android auto compatible vehicle. Looks like there's an emulator, so that's good for as far as it goes. Usually need actual devices to find the rough edges though. https://developer.android.com/training/cars/testing

**Comment by KoalaBear84** [comment] 2019-12-30 05:42
Hmm. I left a review on Google Play that it crashes a lot, and the problem in #379 is what I am experiencing also. So I guess 90% of the crashes was because of this, and (probably) not Bluetooth scanning.

I hope the are crash logs so this can be fixed. Where can I find the info for crash logs?

**Comment by rksh** [comment] 2021-02-20 18:19
v2.60 is released should address the android auto stability issues! please retest?

**Comment by rksh** [comment] 2021-08-30 14:51
closing - no further crash reports on theme switch since 2.60.

**Closed by rksh** 2021-08-30 14:51 UTC

**Comment by KoalaBear84** [comment] 2021-08-30 14:52
Why haven't I responded to your message.. Sorry.

Yes. I can confirm 👍👍

**Comment by greaterthanstar** [comment] 2025-06-07 03:58
It is six years later from the original post. AA is much more widespread now. Do any of the devs have an Android Auto capable car now? It would be so awesome to have Wigle's dashboard showing in AA. I mean, it is a war _driving_ app for Pete's sake! :)

What would it take for AA functionality to be considered? Even at a rudimentary level of just showing the dashboard if it detects it is in that mode.

**Comment by rksh** [comment] 2025-06-07 05:12
We looked into this- getting into Android Auto is unlikely for a hobbyist app. There's a difficult and expansive process to qualify.
