### ISSUE TITLE
Pagination is broken on rankings 

### ISSUE THREAD

**Issue by hsiboy** [wiglenet/wigle-wifi-wardriving#584] opened 2023-04-14 14:05 UTC
Android, version 2.71

Rankings counts from 1 to 100, then jumps to 3,701

I know there was a similar issue, when rankings jumped from 100 to 300.

**Comment by rksh** [comment] 2023-04-19 20:58
Duplicate of #582

**Closed by rksh** 2023-04-19 20:58 UTC
